### ISSUE TITLE
lost connection to the implementation

### ISSUE THREAD

**Issue by bjornwiberg** [jonasbkarlsson/ferroamp_operation_settings#53]
## Version of the custom_component

Version 1.5.0

## Configuration
Describe your configuration here.
<img width="703" alt="image" src="https://github.com/user-attachments/assets/0af019aa-f3f4-4805-981f-18b1bd5562ac">
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/438c3027-69b1-4c9d-bc23-af3ba15b4d4d">

when trying to reconfigure this error message appears
![image](https://github.com/user-attachments/assets/988c2bd2-192a-4b60-b4ca-a75a0cff037c)

Same if i trying to add a new entry
![image](https://github.com/user-attachments/assets/bc86e5ce-a777-4a17-818c-e51c13c62fb1)

## Describe the bug
The implementation stopped work
<img width="357" alt="image" src="https://github.com/user-attachments/assets/2aa4592b-ec4c-4c01-bfdd-25b46edf72b6">

i am able to login to the normal portal  at https://portal.ferroamp.com

## Debug log

```text
TypeError: Type is not JSON serializable: builtin_function_or_method
2024-09-04 10:21:17.603 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-09-04 10:21:22.613 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-09-04 10:21:27.592 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-09-04 10:21:32.592 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-09-04 10:21:37.596 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-09-04 10:21:42.599 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-09-04 10:21:45.116 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/json.py", line 87, in json_encoder_default
raise TypeError
TypeError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 75, in handle
result = handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 228, in get
body=b"".join((b"[", b",".join(states), b"]")),
^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 219, in <genexpr>
states = (state.as_dict_json for state in hass.states.async_all())
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
val = self.func(instance)
^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 1886, in as_dict_json
return json_bytes(self._as_dict)
^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Type is not JSON serializable: builtin_function_or_method
2024-09-04 10:21:46.134 ERROR (MainThread) [custom_components.ferroamp_operation_settings.helpers] Error parsing information from None - Constructor parameter should be str
2024-09-04 10:21:46.135 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
result: _FlowResultT = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ferroamp_operation_settings/config_flow.py", line 113, in async_step_init
error = await FlowValidator.validate_step_user(self.hass, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ferroamp_operation_settings/helpers/config_flow.py", line 43, in validate_step_user
if await client.async_get_data() is None:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ferroamp_operation_settings/helpers/api.py", line 498, in async_get_data
self._access_token = await self.get_access_token()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ferroamp_operation_settings/helpers/api.py", line 447, in get_access_token
await self.get_new_tokens()
File "/config/custom_components/ferroamp_operation_settings/helpers/api.py", line 283, in get_new_tokens
response = await self.api_wrapper_post_data(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ferroamp_operation_settings/helpers/api.py", line 216, in api_wrapper_post_data
return await self.api_wrapper(
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ferroamp_operation_settings/helpers/api.py", line 103, in api_wrapper
raise exception
File "/config/custom_components/ferroamp_operation_settings/helpers/api.py", line 76, in api_wrapper
response = await self._session.post(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 514, in _request
url = self._build_url(str_or_url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 441, in _build_url
url = URL(str_or_url)
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/yarl/_url.py", line 179, in __new__
raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str
2024-09-04 10:21:47.610 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-09-04 10:21:52.607 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-09-04 10:21:57.601 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
```

**Comment by jonasbkarlsson** [comment]
I had a quick look. The login procedure is changed. Will see if I can fix it.

**Comment by bjornwiberg** [comment]
Thank you so much. This will activate my battery automations again 🙏🙏🙏

**Comment by jonasbkarlsson** [comment]
I have now made a [v1.6.0](https://github.com/jonasbkarlsson/ferroamp_operation_settings/releases/tag/v1.6.0) that I believe should work. Please check!

**Comment by bjornwiberg** [comment]
Works. Thank you so much 🔥
